### ISSUE TITLE
Zaključek projekta

### ISSUE THREAD

**Issue by ZanKramar** [jan248/Borza#1]
Pozdravljeni.

Mi bi radi zaključili naš projekt, ali imate še kakšne predloge?
Za dostop do uporabniškega računa uporabite email: 'zan.kramar@gmail.com' in geslo: 'snezinka'. Lahko se pa tudi na novo registrirate.

Lep pozdrav,
Žan Kramar

**Comment by jaanos** [comment]
Aplikacija ne deluje, saj uporabnik `javnost` nima ustreznih pravic na tabelah (glejte npr. pdurcik/Baza-clanstva-RDR#3). Opažam pa, da ima `javnost` pravico `GRANT OPTION` za vse pravice na bazi - to ni zaželeno, saj lahko tako kdorkoli (glede na to, da je geslo javno znano) te pravice dodeljuje naprej. Tako svetujem, da @ZanKramar te pravice odstraniš:
```sql
REVOKE GRANT OPTION FOR ALL ON DATABASE sem2020_zank FROM javnost;
```

Prav tako bi opozoril, da so se vam na repozitorij izmuznile datoteke v mapah `__pycache__` in `.vscode`, ki tja ne sodijo. Tako svetujem, da ti mapi pobrišete; da vam git ne bo znova ponujal teh datotek za dodajanje v commit, poskrbite z ustrezno datoteko `.gitignore` - lahko začnete s [primerom](https://github.com/jaanos/OPB-bottle/blob/master/.gitignore) iz vzorca ter dodaste še vrstico `.vscode`.

Svetoval bi še, da poskrbite, da bo mogoče aplikacijo poganjati v Binderju. V ta namen iz vzorca skopirajte mapo [`binder`](https://github.com/jaanos/OPB-bottle/tree/master/binder) ter popravite datoteko `start`, da bo zagnala vaš program (namesto `primer.py` torej uporabite `start.py`). V `requirements.txt` lahko dodaste še morebitne Pythonove pakete, ki so potrebni za poganjanje vašega programa - mislim sicer, da to pri vas ne bo potrebno. Da bo povezava na bazo delovala, bo potrebno pridobiti [nastavitve iz okolja](https://github.com/jaanos/OPB-bottle/blob/ec3e3d35d3a58502b1aa5fd03a80846b5e68bf39/primer.py#L17-L20) (tj., kar je nastavljeno v `start`) in jih uporabiti pri [povezovanju na bazo](https://github.com/jaanos/OPB-bottle/blob/ec3e3d35d3a58502b1aa5fd03a80846b5e68bf39/primer.py#L70-L75). Potem lahko v `README.md` dodaste še povezavo za poganjanje aplikacije v Binderju:
```markdown
[![bottle.py](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/jan248/Borza/master?urlpath=proxy/8080/)
```

**Comment by ZanKramar** [comment]
Pozdravljeni.

Popravil sem vse, kar ste navedli in sedaj aplikacija dela na mojem localhostu preko uporabnika 'javnost'. Upošteval sem vaša navodila in spremenil datoteko start da uporabi našo datoteko core.py, v katero sem dodal vaše popravke. V repozitorij sem dodal tudi vašo datoteko bottle.py. Ko poženem binder za prvo stran ne uporabi našega css in drugih strani ne najde. Kako lahko to popravimo?

Lep pozdrav,
Žan Kramar

**Comment by jaanos** [comment]
Povezave bo potrebno narediti absolutne - začeti jih bo potrebno s potjo iz spremenljivke `ROOT`. Pomagate si lahko s funkcijo [`rtemplate`](https://github.com/jaanos/OPB-bottle/blob/ec3e3d35d3a58502b1aa5fd03a80846b5e68bf39/primer.py#L25-L29) kot v vzorcu (uporabite jo namesto `template`), ki poleg ostalih podanih spremenljivk v predlogi nastavi še `ROOT`, tako da lahko to spremenljivko podaste pred potmi (za hiperpovezave, slike, CSS, Javascript itd. - poglejte si v vzorcu). Prav tako bo potrebno `ROOT` dodati pri klicih funkcije `redirect` (po potrebi lahko definirate še svojo funkcijo, analogno z `rtemplate`).

**Comment by ZanKramar** [comment]
Hvala za pomoč, sedaj tudi binder dela. Ali je še kaj ali se lahko s profesorjem začnemo dogovarjati o ustnem izpitu?

**Comment by jaanos** [comment]
Prijava pri meni ne deluje - težava je tukaj:
https://github.com/jan248/Borza/blob/b0ee4fb3fac75054d90a36796140a28fbf07c917/core.py#L162
Ker je privzeta vrednost za `ROOT` enaka `/`, se podana pot začne z `//`, kar Linux očitno razume kot pot na lokalnem omrežju. Poskrbite torej, da za `ROOT` nikjer nimate `/` (se pojavi še na nekaj mestih v `core.py`, po predlogah pa nisem preverjal). Poleg tega pri enem `redirect`u manjka `ROOT`:
https://github.com/jan248/Borza/blob/b0ee4fb3fac75054d90a36796140a28fbf07c917/core.py#L479

Poleg tega imam še sledeče pripombe:

* Kolikor vidim, so vnosi v tabelah `prijava` in `uporabnik` v razmerju eden na eden, tako da bi bilo smiselno ti tabeli združiti. Glavni ključ naj bo seveda `id` - na `mail` lahko daste določilo `UNIQUE`. Razmislite tudi o tem, da gesel ne bi hranili v bazi v nezakriti obliki.

* Transakcije bi bilo smiselno ločiti na dve tabeli, eno za gotovinske dvige in pologe, drugo za delnice. Tako se znebite stolpca `tip` in vrednosti `NULL` pri gotovinskih transakcijah. Namesto na račun naj bo referenca na uporabnika kar njegov ID (reference na kratke nize, kot so oznake delnic, so sprejemljive).

* V tabeli `sektor` podatki niso bili uvoženi s pravim kodiranjem znakov. Svetujem, da jih še enkrat uvozite, pri čemer pazite, da odprete datoteko `opisi.sql` tako, da bodo šumniki pravilno prikazani.

* Do težav s kodiranjem znakov pride tudi pri vnosnih poljih, npr. pri registraciji. V ta namen namesto npr. `request.forms.get('ime')` uporabite `request.forms.ime`, kar bi moralo rešiti težave.

* Če pride do napake ob registraciji (prekratko geslo itd.), bi bilo dobro, če se polja napolnijo s podatki, ki jih je vnesel uporabnik, da jih lahko ta samo popravi.

* Podobno naredite tudi pri obrazcih za dvig/polog in trgovanje z delnicami. Morda bi bilo smiselno, da prikažete samo eno vnosno polje za količino, tip (dvig/polog ali prodaja/nakup) pa si uporabnik izbere (npr. z izbirnikom ali *radio button*).

* Če pri trgovanju z delnicami vnesem napačno geslo, pride do napake, saj ni navedena vrednost `stevilo_delnic`:
https://github.com/jan248/Borza/blob/b0ee4fb3fac75054d90a36796140a28fbf07c917/core.py#L418-L431

* Na profilu bi bilo smiselno, če bi bilo možno klikniti na delnice, s katerimi je uporabnik trgoval.

**Comment by ZanKramar** [comment]
Pozdravljeni.

Popravil sem vse, z izjemo točke:

Če pride do napake ob registraciji (prekratko geslo itd.), bi bilo dobro, če se polja napolnijo s podatki, ki jih je vnesel uporabnik, da jih lahko ta samo popravi.

Ali bi mi prosim lahko svetovali, kako naj se tega sploh lotim? Gledal sem že neke rešitve, a php-ja ne poznam dovolj.

Lep pozdrav,
Žan Kramar

**Comment by jaanos** [comment]
Registracija še vedno ne deluje - problem je tukaj:
https://github.com/jan248/Borza/blob/a1d06ce6cd5b64e625d351c2c0964cb9189f2ae5/core.py#L265
Poleg tega nastavite še glavni ključ v tabeli transakcij z delnicami - potem `UNIQUE` ni več potreben (enako tudi pri denarnih transakcijah).

Opažam še, da se geslo pri trgovanju z delnicami ne preveri. Če pa ne izberem nakupa ali prodaje (oziroma dviga ali pologa pri denarnih transakcijah), se prikaže samo prazna stran - smiselno bi se seveda bilo vrniti na isto stran, kjer se izpiše ustrezna napaka.

Kar se tiče izpolnjevanja polj, to naredite enostavno tako, da k `rtemplate` podaste vse podatke iz polj kot spremenljivke - seveda bo potrebno to narediti tudi pri prvotnem prikazu obrazca, kjer bodo spremenljivke prejele prazne nize. Glede na to, da je polj veliko, klicev `rtemplate` pa prav tako, bo najbolje, da si pripravite slovar s podatki. Za začetek si lahko nekje izven funkcij pripravite seznam polj:
```python
polja_registracija = ("ime", "priimek", "mail", "drzava", "trr", "pass1", "pass2")
```
Pri prikazu praznega obrazca (funkcija `register`) lahko potem pripravite slovar s praznimi nizi in ga podaste za vrednosti spremenljivk v predlogi:
```python
    podatki = {polje: "" for polje in polja_registracija}
    return rtemplate('registracija.html', stanje=stanje, napaka=0, **podatki)
```
Pri sami registraciji lahko potem v eni vrstici pridobite vse podatke iz obrazca:
```
    podatki = {polje: getattr(request.forms, polje) for polje in polja_registracija}
```
V predlogo jih potem pošljete na isti način. Seveda bo potrebno sedaj posamezne spremenljivke nadomestiti s polji slovarja. Sedaj lahko polja v predlogi napolnite z ustreznimi podatki, npr.
```html
    <span>Ime:</span><input name='ime' type='text' value='{{ime}}' />
```
Podobno lahko naredite tudi pri drugih obrazcih. Za izbirne gumbe lahko potem uporabite atribut `checked`, če so bili izbrani:
```html
<input type='radio' name='vrsta' value='nakup' id='vrsta' {{'checked' if vrsta == 'nakup' else ''}}>
```

Še to - trenutno preverjate, ali naslov oziroma račun že obstaja tako, da greste čez celotno bazo in primerjate:
https://github.com/jan248/Borza/blob/a1d06ce6cd5b64e625d351c2c0964cb9189f2ae5/core.py#L238-L251
Veliko bolj učinkovito bo, če enostavno podaste pogoj `WHERE`, s katerim primerjate z želeno vrednostjo (lahko naredite kar eno poizvedbo za oba pogoja - torej naslov ali račun se mora ujemati). S `cur.fetchone()` potem dobite eno vrstico - če je rezultat `None`, potem veste, da ujemanja ni (torej se uporabnik lahko registrira), sicer pa lahko primerjate podatke in na podlagi tega ugotovite, katero napako boste izpisali.

Kar se tiče samega vpisovanja uporabnika v tabelo, vidim, da na roke povečujete števec in nato dodaste dobljeni ID. Če bi tabelo uporabnikov naredili tako, da ima stolpec `id` tip `SERIAL` (nastalemu števcu lahko potem ročno nastavite stanje), bi lahko naredili enostavno tako:
```python
        podatki["geslo"] = hashGesla(podatki["pass1"])
        ukaz = """INSERT INTO novi_uporabniki (ime,priimek,drzava,racun,mail,geslo)
                  VALUES((%(ime)s), (%(priimek)s), (%(drzava)s), (%(trr)s), (%(mail)s),(%(geslo)s))
                  RETURNING id"""
        cur.execute(ukaz, podatki)
        uid, = cur.fetchone()
```
Tukaj se uporabi dejstvo, da so podatki za vstavljanje v poizvedbo že v slovarju - niz `%(ime)s` pomeni, da se bo na to mesto vstavilo polje `"ime"` iz podanega slovarja. Stavek `RETURNING` poskrbi, da se poleg dodajanja vrstice vrne tudi vrednost v stolpcu `id` (torej vrednost, generirana s števcem) - to potem dobite s `cur.fetchone()`.

Nazadnje, opažam še, da v vsaki predlogi ponavljate osnovno strukturo - če bi hoteli kaj dodati, bi potem to morali narediti v vsaki predlogi. Svetujem, da namesto tega raje uporabljate ukaz `rebase` (poglejte si, kako je to narejeno v [vzorcu](https://github.com/jaanos/OPB-bottle/tree/master/views)).

**Comment by ZanKramar** [comment]
Pozdravljeni.

Sedaj smo popravili vse kar ste navedli, edino za tip stolpca id pri novi_uporabniki sem nastavil default vrednost vezano na zaporedje, kar deluje enako kot ste vi predlagali.

Lep pozdrav,
Žan Kramar

**Comment by jaanos** [comment]
V redu, sedaj aplikacija deluje, tako da bom dodal povezavo na repozitorij predmeta. Če se še niste, se lahko z @alenFMF domenite za termin zagovora. Če boste do takrat še kaj spreminjali, mi javite, da posodobim povezavo.
